language: node_js
node_js:
  - "8"
  - "10"

before_script:
  - npm run setup
  - npm run lang
  - npm run build

script:
  - npm run test

after_success:
  - bash <(curl -s https://codecov.io/bash)
env:
  matrix:
    secure: UDLCISDmMVCU8nacnzo68VZDxjjEfNyuO87qz1rjcI53la+zvLw9TgVJWGSGIbdZCnSxWN9TKqmpEl/CW/9ShtcXzKwm7QQAzMmk6YlAV/6WyY0yBX6EqZRcnCoGPav2rUEjCia5L1wGbq1HQjUaR95wOiB6+XNob1xJuMJJKRCIIqtdslJh9UMmybjZAlDCRbAFKCJ9CS0TfKtmp2cTzJrhWDzy6JDUfy7DCNueANYubWDsRnQVetzbpEoIO/7hXnclvLAP8d18jiwEhtsQNJ95CRlB++E3z+gpeFxD+L/doXLTgr4d9Zymuus+B4Sj5EbBtWFgqqs1XA9vftNEOCMReg5PG8s0ODiCYRnyHmemLrsdsI7qmMAJycmx6TUfh0Nxg5YmRTFZC7gytQkmgHkFSRRTS3tZlK4W4BH5Y5mm4t6WUPZDIyOpUw9CGSfuTJL7kfu0b1qPcnlVw3l0mHMe/h8pUBfITyoMI2zvnYI2lXm77tIW0dHlsuZrz4xbpXXzf6ayNn1E5l+mFrXY2MpiNVADDOcOwx+7KcBG7hoD5XZGgA5D+ZlkPdI6c60ngO/cP7xseZeLv34yjq+BX9emJqxD30C4X7AaO94HpUX1X304HDWXHwfqIfNa2IzC0F2qq1VWtT4xdxdRlABk8E33PJad6/Cd7dMx+V9y2UU=
